### ISSUE TITLE
Maybe offline playable?

### ISSUE THREAD

**Issue by ColinSegieth** [TyrealGray/AssassinWar#2]
Could you please add an offline game mode, where you hunt AI`s?

**Comment by TyrealGray** [comment]
Hi, do you mean my HMIYC project offline AI? Or this project?
HMIYC is only able to play with your friend in LAN, I haven't implement any AI relative stuff.

And this project is far away from finished because I don't have vs2010 and QT4.8.5 on my computer anymore.

Do you have interest to build a game like this? I am happy to help.

**Comment by ColinSegieth** [comment]
Yeah, I would love to make a game like this, but first, I have plans for
another game. If you want to help me, you're welcome

Am 12.09.2017 17:05 schrieb "Tyreal" <notifications@github.com>:
